"""
HTML-based video generation: Claude script+HTML, duration injection, Playwright record, mux with audio.
Replaces Runway Veo with motion-graphics HTML generated by Claude Opus.
"""

import json
import logging
import os
import re
import subprocess
from pathlib import Path
from typing import Any, List

logger = logging.getLogger(__name__)

# Placeholder strings in generated HTML that we replace with real durations after TTS
SCENE_DURATIONS_PLACEHOLDER = "SCENE_DURATIONS_PLACEHOLDER"
TOTAL_DURATION_PLACEHOLDER = "TOTAL_DURATION_PLACEHOLDER"

# Max paper length to avoid context limits (match scenes.py)
MAX_PAPER_LENGTH = 50000

# Viewport for recording (9:16 vertical)
VIEWPORT_WIDTH = 720
VIEWPORT_HEIGHT = 1280


def _get_reference_html_path() -> Path:
    """Path to reference motion-graphics HTML for style (optional)."""
    base = Path(__file__).resolve().parent.parent
    return base / "miscell" / "Exercise Study - Motion Graphics Video.html"


def _load_reference_html_snippet(max_chars: int = 12000) -> str:
    """Load a truncated reference HTML for the Claude prompt."""
    path = _get_reference_html_path()
    if not path.exists():
        return (
            "Use a structure: .video-container (fixed size), .scene divs with one .active, "
            "CSS transitions for opacity, a progress bar, JS that advances scenes by time and does NOT loop."
        )
    text = path.read_text(encoding="utf-8")
    if len(text) > max_chars:
        text = text[:max_chars] + "\n<!-- ... truncated ... -->"
    return text


def generate_script_and_html(paper_data: dict, output_dir: Path, api_key: str | None = None) -> None:
    """
    Call Claude once to generate script (JSON) and motion-graphics HTML with placeholder durations.
    Writes script.json and motion_video.html to output_dir.
    """
    if api_key is None:
        api_key = os.getenv("ANTHROPIC_API_KEY")
    if not api_key:
        raise ValueError("ANTHROPIC_API_KEY environment variable not set")

    title = paper_data.get("title") or ""
    full_text = paper_data.get("full_text") or ""
    if len(full_text) > MAX_PAPER_LENGTH:
        full_text = full_text[:MAX_PAPER_LENGTH] + "\n\n[Truncated...]"

    reference_snippet = _load_reference_html_snippet()

    prompt = f"""You are creating a short social media video (TikTok/Instagram style) that tells the story of a scientific paper. You will output TWO things: (1) a script as JSON, and (2) a single self-contained HTML file (motion graphics) that displays the scenes. The reference HTML below is for STYLE and ANIMATION only—create NEW structure and content tailored to THIS paper, not the same frames.

PAPER TITLE: {title}

PAPER CONTENT:
{full_text}

NARRATIVE GUIDELINES (same as reference):
1. THE PROBLEM/HOOK (1-2 scenes): Why we should care. Real-world problem or challenge.
2. THE RESEARCH (2-3 scenes): Introduce the study; mention journal and/or researchers for credibility.
3. KEY FINDINGS (2-3 scenes): Main results.
4. THE IMPACT/WHAT'S NEXT (1-2 scenes): What researchers showed, significance, or future work.

Use short, punchy sentences. Avoid jargon. Make it conversational.

REFERENCE HTML (style only—match transitions, progress bar, gradients, typography; do NOT copy content):
```
{reference_snippet}
```

OUTPUT FORMAT (strict):
First output the script as JSON, then the full HTML.

---SCRIPT---
A single JSON array of scene objects. Each object MUST have exactly these keys:
- "text": string (narration for this scene)
- "visual_type": "generated"
- "visual_content": string (short visual hint, e.g. "hook with headline", "bar chart", "stat card")

Create 4-10 scenes. Example:
[{{"text": "Tsetse flies are a huge problem in Tanzania.", "visual_type": "generated", "visual_content": "hook with dramatic headline"}}, ...]

---HTML---
A complete, self-contained HTML file (inline CSS and JS). Requirements:
- One .video-container with fixed dimensions (e.g. 400px x 711px or 720x1280). Use class "scene" for each scene div; only one scene has class "active" at a time. Advance which scene is .active based on elapsed time.
- In the JavaScript, you MUST use these exact placeholder names so we can replace them after TTS:
  const sceneDurations = SCENE_DURATIONS_PLACEHOLDER;   // will be replaced with e.g. [5, 5, 5, 6, 5]
  const totalDuration = TOTAL_DURATION_PLACEHOLDER;      // will be replaced with e.g. 26
- Use placeholder values for now: equal durations per scene (e.g. 5 seconds each) and totalDuration = sum of those. We will replace with real values later.
- Do NOT loop: when totalDuration is reached, leave the last scene visible and stop the timer.
- Auto-start playback shortly after load (e.g. setTimeout to start after 0.5s).
- Include a progress bar that fills over totalDuration.
- Match the motion-graphics style of the reference (gradients, animations, clean typography).
Output the full HTML document (DOCTYPE, html, head, body, all CSS and JS inline). Do not use markdown code fences around the HTML."""

    try:
        from anthropic import Anthropic
    except ImportError:
        raise ImportError("anthropic package is required. Install with: pip install anthropic")

    client = Anthropic(api_key=api_key)
    # #region agent log
    _model = os.getenv("CLAUDE_VIDEO_MODEL", "claude-sonnet-4-20250514")
    _logpath = Path(__file__).resolve().parent.parent / ".cursor" / "debug.log"
    try:
        _logpath.parent.mkdir(parents=True, exist_ok=True)
        with open(_logpath, "a") as _f:
            _f.write(
                '{"id":"log_claude_model","timestamp":' + str(int(__import__("time").time() * 1000)) + ',"location":"html_video.py:client.messages.create","message":"Claude model id used","data":{"model":"' + _model.replace('"', '\\"') + '"},"hypothesisId":"A"}\n'
            )
    except Exception as _e:
        logger.debug("Debug log write failed: %s", _e)
    # #endregion
    logger.info("Calling Claude API to generate script and HTML")

    response = client.messages.create(
        model=_model,
        max_tokens=8192,
        messages=[{"role": "user", "content": prompt}],
    )

    text = response.content[0].text if response.content else ""

    # Parse ---SCRIPT--- ... ---HTML--- (preferred), with fallbacks if Claude omits delimiters
    script_raw = None
    html_raw = None

    script_match = re.search(r"---SCRIPT---\s*(.*?)\s*---HTML---", text, re.DOTALL)
    if script_match:
        script_raw = script_match.group(1).strip()
        html_start = text.find("---HTML---") + len("---HTML---")
        html_raw = text[html_start:].strip()
    else:
        # Fallback: find first valid JSON array of scene objects, then HTML from <!DOCTYPE or <html
        def _find_first_json_array(s: str) -> str | None:
            start = s.find("[")
            while start >= 0:
                depth = 0
                i = start
                in_str = False
                escape = False
                quote = None
                while i < len(s):
                    c = s[i]
                    if escape:
                        escape = False
                        i += 1
                        continue
                    if c == "\\" and in_str:
                        escape = True
                        i += 1
                        continue
                    if not in_str and c in ("'", '"'):
                        in_str = True
                        quote = c
                        i += 1
                        continue
                    if in_str and c == quote:
                        in_str = False
                        i += 1
                        continue
                    if not in_str:
                        if c == "[":
                            depth += 1
                        elif c == "]":
                            depth -= 1
                            if depth == 0:
                                candidate = s[start : i + 1]
                                try:
                                    data = json.loads(candidate)
                                    if isinstance(data, list) and data and isinstance(data[0], dict) and "text" in data[0]:
                                        return candidate
                                except (json.JSONDecodeError, IndexError, KeyError):
                                    pass
                                start = s.find("[", i + 1)
                                break
                    i += 1
                else:
                    break
            return None

        script_raw = _find_first_json_array(text)
        if script_raw:
            # HTML: from first <!DOCTYPE or <html (case-insensitive) to end
            html_match = re.search(r"(<!DOCTYPE\s+html[^>]*>.*|<html[\s>].*)", text, re.DOTALL | re.IGNORECASE)
            if html_match:
                html_raw = html_match.group(1).strip()
            else:
                idx = text.find(script_raw) + len(script_raw)
                tail = text[idx:].strip()
                for strip in (r"^```\s*", r"^```html\s*", r"^```\w*\s*"):
                    tail = re.sub(strip, "", tail, flags=re.IGNORECASE).strip()
                if tail.startswith("```"):
                    tail = tail.lstrip("`").strip()
                html_raw = tail if len(tail) > 400 else None
        if script_raw is None or html_raw is None or len(html_raw or "") < 400:
            raise ValueError("Claude response missing ---SCRIPT--- or ---HTML--- sections (and fallback could not find valid script + HTML)")

    # Strip markdown code fences from script if present
    if script_raw.startswith("```"):
        lines = script_raw.split("\n")
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        script_raw = "\n".join(lines)

    # Parse script JSON
    try:
        scenes_data = json.loads(script_raw)
    except json.JSONDecodeError as e:
        raise ValueError(f"Claude script is not valid JSON: {e}") from e

    if not isinstance(scenes_data, list) or not scenes_data:
        raise ValueError("Claude script must be a non-empty JSON array of scenes")

    # Normalize to Scene-compatible shape (text, visual_type, visual_content)
    normalized = []
    for i, s in enumerate(scenes_data):
        if not isinstance(s, dict):
            raise ValueError(f"Scene {i} is not an object")
        text = s.get("text") or ""
        visual_type = s.get("visual_type") or "generated"
        visual_content = s.get("visual_content") or ""
        normalized.append({"text": text, "visual_type": visual_type, "visual_content": visual_content})
    scenes_data = normalized

    # Strip markdown code fences from HTML
    if html_raw.startswith("```"):
        lines = html_raw.split("\n")
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].strip() == "```":
            lines = lines[:-1]
        html_raw = "\n".join(lines)

    output_dir.mkdir(parents=True, exist_ok=True)

    script_path = output_dir / "script.json"
    with open(script_path, "w", encoding="utf-8") as f:
        json.dump(scenes_data, f, indent=2, ensure_ascii=False)
    logger.info(f"Wrote {script_path} ({len(scenes_data)} scenes)")

    html_path = output_dir / "motion_video.html"
    html_path.write_text(html_raw, encoding="utf-8")
    if html_path.stat().st_size < 500:
        raise ValueError("Generated HTML is too small; likely truncated or invalid")
    logger.info(f"Wrote {html_path}")


def inject_durations(html_path: Path, metadata_path: Path) -> None:
    """
    Replace SCENE_DURATIONS_PLACEHOLDER and TOTAL_DURATION_PLACEHOLDER in the HTML
    with real values from audio_metadata.json.
    """
    if not metadata_path.exists():
        raise FileNotFoundError(f"Metadata file not found: {metadata_path}")

    with open(metadata_path, "r", encoding="utf-8") as f:
        metadata = json.load(f)

    boundaries = metadata.get("scene_boundaries", [])
    total = float(metadata.get("total_duration", 0))

    scene_durations = []
    for b in boundaries:
        dur = b.get("duration") or b.get("clip_duration")
        if dur is not None:
            scene_durations.append(round(float(dur), 2))
        else:
            start = float(b.get("start_time", 0))
            end = float(b.get("end_time", 0))
            scene_durations.append(round(end - start, 2))

    if not scene_durations:
        raise ValueError("audio_metadata.json has no scene boundaries")

    html = html_path.read_text(encoding="utf-8")

    array_str = json.dumps(scene_durations)
    total_str = str(round(total, 2))

    # Prefer exact placeholders; fallback to regex when Claude uses literal numbers
    if SCENE_DURATIONS_PLACEHOLDER in html:
        html = html.replace(SCENE_DURATIONS_PLACEHOLDER, array_str)
    else:
        # Replace sceneDurations = [5, 5, ...] or similar with real durations
        scene_re = re.compile(
            r"\bsceneDurations\s*=\s*\[[^\]]*\]",
            re.IGNORECASE,
        )
        if scene_re.search(html):
            html = scene_re.sub("sceneDurations = " + array_str, html, count=1)
        else:
            raise ValueError(
                "HTML does not contain SCENE_DURATIONS_PLACEHOLDER or sceneDurations = [...]; cannot inject durations"
            )

    if TOTAL_DURATION_PLACEHOLDER in html:
        html = html.replace(TOTAL_DURATION_PLACEHOLDER, total_str)
    else:
        total_re = re.compile(
            r"\btotalDuration\s*=\s*[\d.]+\s*;",
            re.IGNORECASE,
        )
        if total_re.search(html):
            html = total_re.sub("totalDuration = " + total_str + ";", html, count=1)
        else:
            # Try without trailing semicolon (e.g. const totalDuration = 26\n)
            total_re2 = re.compile(r"\btotalDuration\s*=\s*[\d.]+", re.IGNORECASE)
            if total_re2.search(html):
                html = total_re2.sub("totalDuration = " + total_str, html, count=1)
            else:
                raise ValueError(
                    "HTML does not contain TOTAL_DURATION_PLACEHOLDER or totalDuration = <number>; cannot inject durations"
                )

    html_path.write_text(html, encoding="utf-8")
    logger.info(f"Injected {len(scene_durations)} scene durations and total {total_str}s into {html_path}")


def record_html_to_video(
    html_path: Path,
    output_path: Path,
    total_duration_sec: float,
    viewport_width: int = VIEWPORT_WIDTH,
    viewport_height: int = VIEWPORT_HEIGHT,
) -> None:
    """
    Open the HTML file in headless Chromium, record the viewport for total_duration_sec, save as MP4.
    """
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        raise ImportError("playwright package is required. Install with: pip install playwright && playwright install chromium")

    html_path = html_path.resolve()
    if not html_path.exists():
        raise FileNotFoundError(f"HTML file not found: {html_path}")

    # file:// URL
    file_url = html_path.as_uri()

    output_path = output_path.resolve()
    output_path.parent.mkdir(parents=True, exist_ok=True)

    # Playwright saves to record_video_dir; get path after context close.
    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(
            viewport={"width": viewport_width, "height": viewport_height},
            record_video_dir=str(output_path.parent),
            record_video_size={"width": viewport_width, "height": viewport_height},
        )
        page = context.new_page()
        video = page.video
        page.goto(file_url, wait_until="networkidle", timeout=15000)
        page.wait_for_timeout(500)
        page.wait_for_timeout(int((total_duration_sec + 1.0) * 1000))
        page.close()
        context.close()
        video_path = video.path() if video else None
        browser.close()

        if video_path and Path(video_path).exists():
            Path(video_path).rename(output_path)
        else:
            # Fallback: find newest video in output_dir (Playwright may save as .webm)
            parent = output_path.parent
            videos = list(parent.glob("*.webm")) + list(parent.glob("*.mp4"))
            if not videos:
                raise FileNotFoundError("Playwright did not save a video file")
            latest = max(videos, key=lambda p: p.stat().st_mtime)
            latest.rename(output_path)

    logger.info(f"Recorded video to {output_path}")


def mux_audio_with_video(
    video_path: Path,
    audio_path: Path,
    output_path: Path,
) -> None:
    """Combine a silent video with an audio file into final_video.mp4 using ffmpeg."""
    video_path = Path(video_path).resolve()
    audio_path = Path(audio_path).resolve()
    output_path = Path(output_path).resolve()

    if not video_path.exists():
        raise FileNotFoundError(f"Video file not found: {video_path}")
    if not audio_path.exists():
        raise FileNotFoundError(f"Audio file not found: {audio_path}")

    output_path.parent.mkdir(parents=True, exist_ok=True)

    cmd = [
        "ffmpeg",
        "-y",
        "-i", str(video_path),
        "-i", str(audio_path),
        "-map", "0:v",
        "-map", "1:a",
        "-c:v", "copy",
        "-c:a", "aac",
        "-shortest",
        str(output_path),
    ]
    result = subprocess.run(cmd, capture_output=True, text=True)
    if result.returncode != 0:
        raise subprocess.CalledProcessError(
            result.returncode, cmd, result.stdout, result.stderr
        )
    logger.info(f"Muxed audio onto video: {output_path}")


def run_html_video_step(output_dir: Path) -> None:
    """
    Run the full "generate-videos" step for HTML pipeline: inject durations, record HTML to video.
    Requires: motion_video.html, audio_metadata.json, audio.wav in output_dir.
    Produces: recorded.mp4 in output_dir (the playable recording; no final_video.mp4 mux step).
    """
    output_dir = Path(output_dir)
    html_path = output_dir / "motion_video.html"
    metadata_path = output_dir / "audio_metadata.json"
    recorded_path = output_dir / "recorded.mp4"

    if not html_path.exists():
        raise FileNotFoundError(f"motion_video.html not found in {output_dir}")
    if not metadata_path.exists():
        raise FileNotFoundError(f"audio_metadata.json not found in {output_dir}")

    with open(metadata_path, "r", encoding="utf-8") as f:
        meta = json.load(f)
    total_duration = float(meta.get("total_duration", 0))
    if total_duration <= 0:
        raise ValueError("audio_metadata.json total_duration must be positive")

    inject_durations(html_path, metadata_path)
    record_html_to_video(html_path, recorded_path, total_duration)

    logger.info(f"HTML video step complete: {recorded_path}")
